package com.yugahashimoto.andcode.runtime.local

import com.yugahashimoto.andcode.core.api.OpenCodeCommand

/**
 * Hermes slash-command catalogue from hermes_cli.commands.COMMAND_REGISTRY.
 * Shown in the composer `/` popup when Hermes is the active agent.
 */
object HermesCommandCatalog {
    val commands: List<OpenCodeCommand> =
        listOf(
            OpenCodeCommand(name = "start", description = "Acknowledge platform start pings without a reply"),
            OpenCodeCommand(name = "new", description = "Start a new session (fresh session ID + history)"),
            OpenCodeCommand(name = "topic", description = "Enable or inspect Telegram DM topic sessions"),
            OpenCodeCommand(name = "clear", description = "Clear screen and start a new session"),
            OpenCodeCommand(name = "redraw", description = "Force a full UI repaint (recovers from terminal drift)"),
            OpenCodeCommand(name = "history", description = "Show conversation history"),
            OpenCodeCommand(name = "save", description = "Export the current conversation (bare /save shows usage)"),
            OpenCodeCommand(name = "retry", description = "Retry the last message (resend to agent)"),
            OpenCodeCommand(name = "prompt", description = "Compose your next prompt in ${'$'}EDITOR (markdown), then send it"),
            OpenCodeCommand(name = "undo", description = "Back up N user turns and re-prompt (default 1)"),
            OpenCodeCommand(name = "title", description = "Set a title for the current session"),
            OpenCodeCommand(
                name = "handoff",
                description = "Hand off this session to a messaging platform (Telegram, Discord, etc.)",
            ),
            OpenCodeCommand(name = "branch", description = "Branch the current session (explore a different path)"),
            OpenCodeCommand(name = "worktree", description = "Show, list, create, or prune isolated git worktrees"),
            OpenCodeCommand(
                name = "compress",
                description = "Compress conversation context (add 'here [N]' to keep recent N turns; --preview shows what would happen)",
            ),
            OpenCodeCommand(
                name = "rollback",
                description = "List or restore filesystem checkpoints (restores keep your hand-edits; --all overrides)",
            ),
            OpenCodeCommand(name = "snapshot", description = "Create or restore state snapshots of Hermes config/state"),
            OpenCodeCommand(name = "export", description = "Export a profile (config, skills, theme) to a shareable archive"),
            OpenCodeCommand(name = "import", description = "Import a shared profile archive as a new profile"),
            OpenCodeCommand(name = "stop", description = "Kill all running background processes"),
            OpenCodeCommand(name = "pause", description = "Pause new work globally (emergency stop); '/pause off' resumes"),
            OpenCodeCommand(name = "approve", description = "Approve a pending dangerous command"),
            OpenCodeCommand(name = "deny", description = "Deny a pending dangerous command (optionally with a reason)"),
            OpenCodeCommand(name = "bg", description = "Run a prompt in a separate background session"),
            OpenCodeCommand(
                name = "btw",
                description = "Ask a side question about the current conversation without interrupting it",
            ),
            OpenCodeCommand(name = "agents", description = "Show active agents and running tasks"),
            OpenCodeCommand(name = "journey", description = "Open the learning journey timeline"),
            OpenCodeCommand(
                name = "queue",
                description = "Queue a prompt for the next turn, or list/edit/rm/move/clear queued prompts",
            ),
            OpenCodeCommand(name = "steer", description = "Inject a message after the next tool call without interrupting"),
            OpenCodeCommand(name = "goal", description = "Set a standing goal Hermes works on across turns until achieved"),
            OpenCodeCommand(name = "heartbeat", description = "Set a recurring prompt that re-enters this session when idle"),
            OpenCodeCommand(name = "refine", description = "Review this conversation now and save lessons to memory/skills"),
            OpenCodeCommand(
                name = "review",
                description = "Spawn an independent subagent to review the work just discussed (PR, code, docs)",
            ),
            OpenCodeCommand(name = "loop", description = "Re-run a prompt on a recurring interval in this session"),
            OpenCodeCommand(
                name = "plan",
                description = "Write a markdown implementation plan to .hermes/plans/ without executing anything",
            ),
            OpenCodeCommand(
                name = "moa",
                description = "Run one prompt through the default Mixture of Agents preset, then restore your model",
            ),
            OpenCodeCommand(name = "subgoal", description = "Add or manage extra criteria on the active goal"),
            OpenCodeCommand(name = "status", description = "Show session, model, token, and context info"),
            OpenCodeCommand(name = "egress", description = "Show Docker egress proxy status"),
            OpenCodeCommand(
                name = "context",
                description = "Show detailed context window view with usage gauge, category breakdown, compression stats, and throughput",
            ),
            OpenCodeCommand(name = "whoami", description = "Show your slash command access (admin / user)"),
            OpenCodeCommand(name = "profile", description = "Show active profile name and home directory"),
            OpenCodeCommand(name = "sethome", description = "Set this chat as the home channel"),
            OpenCodeCommand(name = "resume", description = "Resume a previously-named session"),
            OpenCodeCommand(name = "sessions", description = "Browse and resume previous sessions"),
            OpenCodeCommand(name = "config", description = "Show current configuration"),
            OpenCodeCommand(name = "model", description = "Switch model (session-scoped; --global to persist)"),
            OpenCodeCommand(name = "codex-runtime", description = "Toggle codex app-server runtime for OpenAI/Codex models"),
            OpenCodeCommand(name = "personality", description = "Set a predefined personality"),
            OpenCodeCommand(name = "statusbar", description = "Toggle the context/model status bar"),
            OpenCodeCommand(name = "battery", description = "Toggle a color-coded battery indicator in the status bar"),
            OpenCodeCommand(name = "timestamps", description = "Toggle [HH:MM] timestamps on messages and /history"),
            OpenCodeCommand(name = "diff", description = "Show git changes in the working directory"),
            OpenCodeCommand(name = "verbose", description = "Cycle tool progress display: off -> new -> all -> verbose"),
            OpenCodeCommand(name = "focus", description = "Toggle focus view — show only your prompt and the final response"),
            OpenCodeCommand(name = "footer", description = "Toggle gateway runtime-metadata footer on final replies"),
            OpenCodeCommand(name = "yolo", description = "Toggle YOLO mode (skip all dangerous command approvals)"),
            OpenCodeCommand(name = "approvals", description = "Show or set the persistent dangerous-command approval mode"),
            OpenCodeCommand(name = "reasoning", description = "Manage reasoning effort and display"),
            OpenCodeCommand(
                name = "fast",
                description = "Fast mode — OpenAI Priority Processing / Anthropic Fast Mode (normal/fast/auto/cold)",
            ),
            OpenCodeCommand(name = "skin", description = "Show or change the display skin/theme"),
            OpenCodeCommand(name = "indicator", description = "Pick the TUI busy-indicator style"),
            OpenCodeCommand(name = "voice", description = "Toggle voice mode"),
            OpenCodeCommand(name = "wake", description = "Toggle the 'Hey Hermes' wake word listener"),
            OpenCodeCommand(name = "busy", description = "Control how messages behave while Hermes is working"),
            OpenCodeCommand(name = "tools", description = "Manage tools: /tools [list|disable|enable] [name...]"),
            OpenCodeCommand(name = "toolsets", description = "List available toolsets"),
            OpenCodeCommand(name = "skills", description = "Search, install, inspect, or manage skills"),
            OpenCodeCommand(name = "memory", description = "Review pending memory writes / toggle the approval gate"),
            OpenCodeCommand(name = "bundles", description = "List skill bundles (aliases /<name> for multiple skills)"),
            OpenCodeCommand(name = "pet", description = "Toggle or adopt a petdex mascot (/pet, /pet list, /pet <slug>)"),
            OpenCodeCommand(name = "hatch", description = "Generate a new petdex pet from a description"),
            OpenCodeCommand(
                name = "learn",
                description = "Learn a reusable skill from anything you describe (dirs, URLs, this chat, notes)",
            ),
            OpenCodeCommand(name = "init", description = "Generate or update AGENTS.md project instructions from a repo scan"),
            OpenCodeCommand(name = "cron", description = "Manage scheduled tasks"),
            OpenCodeCommand(name = "suggestions", description = "Review suggested automations (accept/dismiss)"),
            OpenCodeCommand(name = "blueprint", description = "Set up an automation from a blueprint template"),
            OpenCodeCommand(
                name = "curator",
                description = "Background skill maintenance (status, run, pin, archive, list-archived)",
            ),
            OpenCodeCommand(name = "kanban", description = "Multi-profile collaboration board (tasks, links, comments)"),
            OpenCodeCommand(name = "reload", description = "Reload .env variables into the running session"),
            OpenCodeCommand(name = "reload-mcp", description = "Reload MCP servers from config"),
            OpenCodeCommand(name = "reload-skills", description = "Re-scan ~/.hermes/skills/ for newly installed or removed skills"),
            OpenCodeCommand(
                name = "browser",
                description = "Connect browser tools to your live Chromium-family browser via CDP, or switch to Browser Use mode",
            ),
            OpenCodeCommand(name = "plugins", description = "List installed plugins and their status"),
            OpenCodeCommand(name = "commands", description = "Browse all commands and skills (paginated)"),
            OpenCodeCommand(
                name = "help",
                description = "Show available commands (/help skills lists skill commands, /help <text> filters)",
            ),
            OpenCodeCommand(name = "palette", description = "Open the fuzzy command palette (also Ctrl+P)"),
            OpenCodeCommand(name = "restart", description = "Gracefully restart the gateway after draining active runs"),
            OpenCodeCommand(
                name = "usage",
                description = "Show token usage and rate limits; `reset` redeems a banked Codex limit reset",
            ),
            OpenCodeCommand(name = "subscription", description = "View your Nous plan and change it in the browser"),
            OpenCodeCommand(name = "login", description = "Sign in with a Nous account (keeps your connectors)"),
            OpenCodeCommand(name = "topup", description = "Show your Nous balance and manage billing on the portal"),
            OpenCodeCommand(name = "insights", description = "Show usage insights and analytics"),
            OpenCodeCommand(name = "platforms", description = "Show gateway/messaging platform status"),
            OpenCodeCommand(name = "platform", description = "Pause, resume, or list a failing gateway platform"),
            OpenCodeCommand(name = "copy", description = "Copy the last assistant response to clipboard"),
            OpenCodeCommand(name = "paste", description = "Attach clipboard image from your clipboard"),
            OpenCodeCommand(name = "image", description = "Attach a local image file for your next prompt"),
            OpenCodeCommand(name = "update", description = "Update Hermes Agent to the latest version"),
            OpenCodeCommand(name = "version", description = "Show Hermes Agent version"),
            OpenCodeCommand(name = "debug", description = "Upload debug report (system info + logs) and get shareable links"),
            OpenCodeCommand(name = "quit", description = "Exit the CLI (use --delete to also remove session history)"),
        )
}
